apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nfox
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-nfox@sha256:7bf1a902a20772d0b08c640e6d659cf92fbf85fdaa939cbe57ee81acaf20f1c8
        name: my-nodejs
        resources: {}
status: {}
